# -*- coding: utf-8 -*-
"""Rock, Paper, Scissors .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oJmdrJynjxhmV1qXH99lwl6WJtIxW9l
"""

# Rock, Paper, Scissors - Two Player Game

while True:
    print("\n=== Rock, Paper, Scissors ===")

    player1 = input("Player 1 - Enter rock, paper, or scissors: ").lower()
    player2 = input("Player 2 - Enter rock, paper, or scissors: ").lower()

    # Check for valid input
    if player1 not in ["rock", "paper", "scissors"] or player2 not in ["rock", "paper", "scissors"]:
        print("Invalid input. Please enter rock, paper, or scissors.")
        continue

    # Determine the winner
    if player1 == player2:
        print("It's a tie!")
    elif (
        (player1 == "rock" and player2 == "scissors") or
        (player1 == "paper" and player2 == "rock") or
        (player1 == "scissors" and player2 == "paper")
    ):
        print("Congratulations! Player 1 wins!")
    else:
        print("Congratulations! Player 2 wins!")

    # Ask to play again
    play_again = input("\nDo you want to play again? (yes/no): ").lower()

    if play_again != "yes":
        print("Thanks for playing!")
        break